### ISSUE TITLE
Default permalink language not working for collections

### ISSUE THREAD

**Issue by git-no** [vwochnik/jekyll-language-plugin#19]
The permalink language setting does not work with **collections**,

Scenario a.) default permalink is set in _config.yml

```
collections:
  mycollection:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      path: "_posts"
      layout: post
      permalink: /:language/:categories/:path/
  - scope:
      path: ""
      type: mycollection
    values:
      layout: page
      permalink: /:language/:collection/:title/
      subset: mycollection
```

`jekyll b`quits with an error

```
Error: could not read file /Users/me/Development/www/_mycollection/master.md: undefined method `language' for #<Jekyll::Drops::UrlDrop:0x007fe40201c028>
jekyll 3.1.2 | Error:  undefined method `language' for #<Jekyll::Drops::UrlDrop:0x007ff375078508>
```

Scenario b) permalink in each file - it works when the permalink is set in each collection **file** in the YAML (which is additional work).
