### ISSUE TITLE
Provide pre-translated strings

### ISSUE THREAD

**Issue by Anthony-Gaudino** [vwochnik/jekyll-language-plugin#8]
How do you like it if I create YAML files containing translated dates, translated language names and maybe other things for most languages?

[Rails-i18n](https://github.com/svenfuchs/rails-i18n/tree/master/rails/locale) provide files with translations for dates and other things.

You will be able to include the files on the plugin or make it available to users, so they can use on their websites.

It would be something like this:

``` YAML

---
en-US:
  language: English
  date:
    abbr_day_names:
    - Sun
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
    - Sat
    abbr_month_names:
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - Jun
    - Jul
    - Aug
    - Sep
    - Oct
    - Nov
    - Dec
    day_names:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    month_names:
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
    prompts:
      day: Day
      hour: Hour
      minute: Minute
      month: Month
      second: Seconds
      year: Year
```

So, if someone wants to create a menu with links for all available languages, they can query the `language` in the YAML and create a list like this:

```
English
Français
Português
```

If you want to, you can even automate the plugin to look for the Jekyll `date` liquid tag and translate the date without the user having to use another liquid tag just for it, but then in this case, the user would need to use the same language names provided by the plugin.

And if you think there's other interesting strings that could be added I will see what I can do.
